from selenium import webdriver
import time
driver=webdriver.Chrome()
driver.get('https://www.skillrack.com/faces/ui/profile.xhtml')
time.sleep(3)
user=driver.find_element_by_xpath('//*[@id="input_j_id_u"]')
user.send_keys('YOUR LOGIN ID')
user.click()
password=driver.find_element_by_xpath('//*[@id="input_j_id_w"]')
password.send_keys('YOUR PASSWORD')
time.sleep(3)
mess=driver.find_element_by_xpath('//*[@id="j_id_y"]')
mess.click()
time.sleep(5)
prog=driver.find_element_by_xpath('//*[@id="j_id_52"]/div/a[2]')
prog.click()
time.sleep(5)
codepad=driver.find_element_by_xpath('//*[@id="j_id_4f"]/div/div[9]/div/div[2]/a')
codepad.click()
time.sleep(5)
strev=driver.find_element_by_xpath('//*[@id="j_id_37:j_id_3a:3:j_id_3i"]')
strev.click()
time.sleep(5)
inp=driver.find_element_by_xpath('//*[@id="j_id_4n"]')
inp.send_keys('apple')
time.sleep(5)
inp.click()
run=driver.find_element_by_xpath('//*[@id="j_id_5i"]/span')
run.click()


